name: Test

on:
- push
- pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        haproxy-versions:
        - "1.8"
        - "1.9"
        - "2.0"
        - "2.1"
    steps:
    - uses: actions/checkout@v2
    - name: Install apt dependencies.
      run: |
        sudo apt-get install -y liblua5.3-dev lua-socket
    - name: Install HAProxy.
      run: |
        curl -fsSL http://www.haproxy.org/download/${HAPROXY_VERSION}/src/snapshot/haproxy-ss-LATEST.tar.gz -o haproxy.tar.gz
        mkdir haproxy
        tar xvf haproxy.tar.gz -C haproxy --strip-components=1
        make -C haproxy -j$(nproc) all TARGET=linux-glibc USE_LUA=1
        sudo make -C haproxy install
      env:
        HAPROXY_VERSION: ${{ matrix.haproxy-versions }}
    - name: Show HAProxy version.
      run: haproxy -vv
    - name: Install VTest.
      run: |
        curl -fsSL https://github.com/vtest/VTest/archive/master.tar.gz -o VTest.tar.gz
        mkdir VTest
        tar xvf VTest.tar.gz -C VTest --strip-components=1
        make -C VTest -j$(nproc) FLAGS="-O2 -s -Wall"
        sudo install -m755 VTest/vtest /usr/bin/vtest
    - name: Run tests.
      run: vtest -Dauth_request_root=$(pwd) -k -t 10 test/*.vtc
